Repository firebase/firebase-functions, pull requests merged in 2019-07, with the labels that each got.

#504 Simplify TypeScript configuration
  tsconfig.json
  tsconfig.release.json
Labels: type: cleanup

#505 Remove redundant fields from ScheduleBuilder
  src/providers/pubsub.ts
Labels: type: cleanup

#506 Enable and apply `noUnusedLocals` compiler option
  spec/apps.spec.ts
  spec/providers/auth.spec.ts
  spec/providers/remoteConfig.spec.ts
  src/cloud-functions.ts
  src/providers/remoteConfig.ts
  tsconfig.release.json
Labels: type: cleanup

#503 Specify files included in the package using opt-in strategy
  .npmignore
  package.json
Labels: type: cleanup

#507 Specify a type of DeploymentOptions.regions more precisely
  src/function-configuration.ts
Labels: type: cleanup

#511 Change @internal => @hidden
  src/apps.ts
  src/cloud-functions.ts
  src/config.ts
  src/function-builder.ts
  src/handler-builder.ts
  src/providers/analytics.ts
  src/providers/auth.ts
  src/providers/crashlytics.ts
  src/providers/database.ts
  src/providers/firestore.ts
  src/providers/https.ts
  src/providers/pubsub.ts
  src/providers/remoteConfig.ts
  src/providers/storage.ts
Labels: type: feature request

#510 Move unexported dependencies on @types to devDependencies
  package.json
Labels: type: cleanup

#509 Run Prettier for all supported file formats
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/---report-a-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierignore
  integration_test/README.md
  integration_test/functions/tsconfig.json
  package.json
  tsconfig.json
Labels: type: cleanup

#513 Remove unused valAt utility
  spec/utils.spec.ts
  src/utils.ts
Labels: type: cleanup

#512 Include all TypeScript files in development configuration
  integration_test/functions/src/auth-tests.ts
  integration_test/functions/src/database-tests.ts
  integration_test/functions/src/firestore-tests.ts
  integration_test/functions/src/https-tests.ts
  integration_test/functions/src/index.ts
  integration_test/functions/src/pubsub-tests.ts
  integration_test/functions/src/remoteConfig-tests.ts
  integration_test/functions/src/storage-tests.ts
  integration_test/functions/src/testing.ts
  tsconfig.json
Labels: type: cleanup

#516 Define Codeowners
  .github/CODEOWNERS
Labels: type: cleanup

#514 Extract and document path manipulation utilities
  spec/index.spec.ts
  spec/utilities/path.spec.ts
  spec/utils.spec.ts
  src/providers/database.ts
  src/utilities/path.ts
  src/utils.ts
Labels: type: cleanup

#491 Add automatic TypeDoc generation to Functions SDK
  .gitignore
  docgen/content-sources/HOME.md
  docgen/content-sources/toc.yaml
  docgen/generate-docs.js
  docgen/theme/assets/css/firebase.css
  docgen/theme/assets/css/main.css
  docgen/theme/assets/images/lockup.png
  docgen/theme/layouts/default.hbs
  docgen/theme/partials/breadcrumb.hbs
  docgen/theme/partials/comment.hbs
  docgen/theme/partials/header.hbs
  docgen/theme/partials/member.sources.hbs
  docgen/theme/partials/navigation.hbs
  docgen/theme/templates/reflection.hbs
  docgen/tsconfig.json
  docgen/typedoc.js
  package.json
  src/providers/auth.ts
Labels: type: feature request

#517 Add code comments for storage events
  src/providers/storage.ts
Labels: documentation

#515 Introduce Mocha configuration file
  .mocharc.yaml
  mocha/setup.ts
  package.json
  spec/index.spec.ts
Labels: type: cleanup

#525 Adding comments to try and populate information for Change and ChangeJson
  docgen/content-sources/toc.yaml
  src/cloud-functions.ts
Labels: documentation

#520 Fix exhaustiveness of error code switch in http status conversion
  src/providers/https.ts
  src/utilities/assertions.ts
Labels: type: cleanup

#524 Adding code comments to remoteConfig.ts source
  src/providers/remoteConfig.ts
Labels: documentation

#527 Em pubsub
  src/providers/pubsub.ts
Labels: documentation

#521 Increase type strictness of HttpsError class
  src/providers/https.ts
Labels: type: cleanup

#531 Adding code comments and @hidden tags for src/providers/database.ts
  src/providers/database.ts
Labels: documentation

#534 Adding code comments to src/providers/crashlytics.ts
  src/providers/crashlytics.ts
Labels: documentation

#535 Adding code comments to analytics.ts
  src/providers/analytics.ts
Labels: documentation
